window.cuestionarioPreguntas = [
  { enunciado: 'Una de las premisas es correcta:', opciones: ['Pasteur es el padre de la microbiología', 'La timina es una base nitrogenada purina.', 'Pasteur es el padre de la botánica', 'El uracilo es una base nitrogenada del ADN', 'Arrhenius propuso la teoría abiogénica.'], respuesta: 0 },
  { enunciado: 'Propuso la teoría quimiosintética:', opciones: ['Charles Darwin', 'Gregor Mendel', 'Alexander Oparin', 'Louis Pasteur', 'Isaac Newton'], respuesta: 2 },
  { enunciado: 'Ciencia que estudia la distribución de los seres vivos en la Tierra:', opciones: ['Ecología', 'Zoología', 'Botánica', 'Biogeografía', 'Genética'], respuesta: 3 },
  { enunciado: 'Conjunto de reacciones químicas y procesos físicos que ocurren en las células para convertir los alimentos y nutrientes en energía y materiales necesarios para la vida:', opciones: ['Digestivo', 'Respiración', 'Metabolismo', 'Circulación', 'Fotosíntesis'], respuesta: 2 },
  { enunciado: 'Capacidad fundamental de todos los seres vivos para detectar y responder a estímulos internos o externos:', opciones: ['Adaptación', 'Reproducción', 'Metabolismo', 'Crecimiento', 'Irritabilidad'], respuesta: 4 },
  { enunciado: 'Ciencia que estudia a Entamoeba histolytica, la ameba parásita:', opciones: ['Malacología', 'Ictiología', 'Aracnología', 'Entomología', 'Protozoología'], respuesta: 4 },
  { enunciado: 'Se encarga del estudio de Iguana iguana, el pacaso:', opciones: ['Carcinología', 'Malacología', 'Ornitología', 'Herpetología', 'Pteridología'], respuesta: 3 },
  { enunciado: '¿Quién propuso la teoría relacionada con Arrhenius?', opciones: ['Charles Darwin', 'Alexander Oparin', 'Svante Arrhenius', 'Louis Pasteur', 'Gregor Mendel'], respuesta: 2 },
  { enunciado: 'Es una premisa verdadera:', opciones: ['Virchow descubrió la célula', 'Aristóteles es considerado padre de la biología', 'Leeuwenhoek inventó el microscopio', 'Lamarck acuñó el término ecología', 'Zacarías descubrió los protozoarios'], respuesta: 1 },
  { enunciado: 'Los hongos presentan reproducción asexual tipo:', opciones: ['Esporulación', 'Fisión binaria', 'Vegetativa', 'Poliembrionía', 'Partenogénesis'], respuesta: 0 },
  { enunciado: 'Rama de la biología y la medicina que estudia la estructura microscópica de los tejidos y células:', opciones: ['Histología', 'Anatomía', 'Citología', 'Fisiología', 'Embriología'], respuesta: 0 },
  { enunciado: 'El término biología fue acuñado de manera independiente a principios del siglo XIX por:', opciones: ['Darwin y Lamarck', 'Lamarck y Treviranus', 'De Vries y Lamarck', 'Dobzhansky y Treviranus', 'Pasteur y Lamarck'], respuesta: 1 },
  { enunciado: 'Es la capacidad de los seres vivos para mantener un entorno interno estable y equilibrado:', opciones: ['Reproducción', 'Hemostasia', 'Homeostasis', 'Irritabilidad', 'Adaptación'], respuesta: 2 },
  { enunciado: 'Es un metal blando, plateado y altamente reactivo, esencial para la vida y conocido por formar la sal de mesa:', opciones: ['Carbono', 'Hidrógeno', 'Nitrógeno', 'Sodio', 'Fósforo'], respuesta: 3 },
  { enunciado: 'Vitamina del complejo B conocida también como biotina:', opciones: ['B1', 'B2', 'B6', 'B3', 'B8'], respuesta: 4 },
  { enunciado: 'Vitamina conocida también como tiamina:', opciones: ['A', 'D', 'B8', 'E', 'B1'], respuesta: 4 },
  { enunciado: 'Forma sintética de la vitamina B9, esencial para la producción de ADN y glóbulos rojos:', opciones: ['Riboflavina', 'Ácido fólico', 'Tiamina', 'Niacina', 'Biotina'], respuesta: 1 },
  { enunciado: 'Polisacárido de reserva de los animales y hongos:', opciones: ['Inulina', 'Almidón', 'Glucógeno', 'Celulosa', 'Quitina'], respuesta: 2 },
  { enunciado: 'La desoxirribosa es:', opciones: ['Un disacárido', 'Una pentosa', 'Una heptosa', 'Una hexosa', 'Un polisacárido'], respuesta: 1 },
  { enunciado: 'Polisacárido de reserva presente solo en las plantas:', opciones: ['Celulosa', 'Quitina', 'Glucógeno', 'Almidón', 'Lactosa'], respuesta: 3 },
  { enunciado: 'Base nitrogenada pirimidina que forma parte del ARN y ADN:', opciones: ['Adenina', 'Guanina', 'Timina', 'Uracilo', 'Citosina'], respuesta: 4 },
  { enunciado: 'Función de las proteínas pepsina y amilasa salival:', opciones: ['Estructural', 'Catalítica', 'Termoaislante', 'Reguladora', 'Movimiento'], respuesta: 1 },
  { enunciado: 'Es un oligosacárido de la caña de azúcar:', opciones: ['Glucosa', 'Fructosa', 'Sacarosa', 'Lactosa', 'Almidón'], respuesta: 2 },
  { enunciado: 'Los omegas 3, 6 y 9 son:', opciones: ['Carbohidratos', 'Proteínas', 'Ácidos nucleicos', 'Ácidos grasos', 'Vitaminas'], respuesta: 3 },
  { enunciado: 'Ácido graso que no tiene la categoría de esencial:', opciones: ['Ácido alfa-linolénico (ALA)', 'Ácido eicosapentaenoico (EPA)', 'Ácido docosahexaenoico (DHA)', 'Ácido graso linoleico (LA)', 'Palmitoleico'], respuesta: 4 },
  { enunciado: 'Es un nucleósido:', opciones: ['ADN', 'ATP', 'Glucosa', 'Adenosina', 'Fosfolípido'], respuesta: 3 },
  { enunciado: 'Es un nucleótido:', opciones: ['Glucosa', 'Adenosina', 'ATP', 'Colágeno', 'Fructosa'], respuesta: 2 },
  { enunciado: 'Es una proteína de reserva:', opciones: ['Histonas', 'Anticuerpo', 'Lactoalbúmina', 'Actina', 'Colágeno'], respuesta: 2 },
  { enunciado: 'Es la proteína de los cromosomas:', opciones: ['Hemoglobina', 'Histona', 'Queratina', 'Insulina', 'Colágeno'], respuesta: 1 },
  { enunciado: 'Proteína cuya función es la contracción muscular y el movimiento:', opciones: ['Miosina', 'Hemocianina', 'Hemoglobina', 'Lipoproteína', 'Mioglobina'], respuesta: 0 },
  { enunciado: 'La deficiencia de vitamina B2 produce:', opciones: ['Queilitis angular', 'Beri beri', 'Ceguera nocturna', 'Raquitismo', 'Xeroftalmia'], respuesta: 0 },
  { enunciado: 'Vitamina denominada también tocoferol:', opciones: ['Vitamina A', 'Vitamina B12', 'Vitamina C', 'Vitamina D', 'Vitamina E'], respuesta: 4 },
  { enunciado: 'A la vitamina ácido nicotínico (B3) se le conoce como:', opciones: ['Ácido fólico', 'Antipelagra', 'Riboflavina', 'Antiescorbútica', 'Biotina'], respuesta: 1 },
  { enunciado: 'Su carencia en la alimentación puede ocasionar el beriberi:', opciones: ['Vitamina A', 'Vitamina B1', 'Vitamina C', 'Vitamina D', 'Vitamina E'], respuesta: 4 },
  { enunciado: 'La vitamina cianocobalamina:', opciones: ['Es una vitamina liposoluble', 'Llamada también ácido ascórbico', 'Es la vitamina de la coagulación sanguínea', 'Su deficiencia produce el escorbuto', 'Es una vitamina hidrosoluble'], respuesta: 1 },
  { enunciado: 'A las vitaminas B2 y B3 se les conoce como, respectivamente:', opciones: ['Antirraquítica - Antixeroftálmica', 'Riboflavina - Niacina', 'Riboflavina - Antixeroftálmica', 'Alfa tocoferol - Tiamina', 'Antixeroftálmica - Tiamina'], respuesta: 4 },
  { enunciado: 'La unión de dos glucosas se realiza mediante el enlace químico:', opciones: ['Peptídico', 'Fosfodiéster', 'Puente de hidrógeno', 'Éster', 'Glucosídico'], respuesta: 1 },
  { enunciado: 'La contrastación de la hipótesis es:', opciones: ['Un planteamiento del problema', 'La observación', 'Una conclusión', 'La experimentación', 'La hipótesis'], respuesta: 4 }
];
